[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = '<a class="text-muted" href="#">Pranav Dhawale</a> | <a class="text-muted" href="https://gajanan-more.github.io/">Gajanan More</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
